pypdns/__init__.py,sha256=57HylGJkFER4MUzY6kMd7LGFsoBQyrru5TtXPNmyuVA,921
pypdns/api.py,sha256=X042qAHm4Z8NIwdSJM-hKDRULG8mSsj2EXGBJai5jTA,17145
pypdns/errors.py,sha256=z1MDSVuN0I553AczIVQhJA4U7JPoChkRAv1dOFaNLPw,474
pypdns/py.typed,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
pypdns-2.2.0.dist-info/LICENSE,sha256=o1p6jKkqoo0k2KXZ23F8zTPaRGIoF8Gu9ADxi-QiUyo,1576
pypdns-2.2.0.dist-info/METADATA,sha256=GqnZp7NCQiRwWfWFZd-FE_ccrX_opKESsLKHcgJvadI,2762
pypdns-2.2.0.dist-info/WHEEL,sha256=d2fvjOD7sXsVzChCqf0Ty0JbHKBaLYwDbGQDwQTnJ50,88
pypdns-2.2.0.dist-info/entry_points.txt,sha256=9MC-9q1FbTVA0TQgOgc4JMUz9comV4RsGdeDel5gdxg,36
pypdns-2.2.0.dist-info/RECORD,,
